# Generated by Django 3.0 on 2022-10-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=500, unique=True)),
                ('date', models.DateField()),
                ('work_status', models.CharField(choices=[('Active Task', 'Active Task'), ('Completed', 'Completed'), ('Upcoming', 'Upcoming')], max_length=150)),
                ('discription', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
